### ISSUE TITLE
只能在django中使用嗎?

### ISSUE THREAD

**Issue by RiceeeChang** [lockys/allPay.py#1]
這個module只能在django framework中使用嗎?
因為你有用到django的setting 
如果我不用django的話 可以做怎樣的修改?

**Comment by lockys** [comment]
@RiceeeChang 
Github 上的版本是針對 Django 做設計的。
若你是用其他的 framework 的話
在[`setting.py`](https://github.com/lockys/pyAllpay/blob/master/pyallpay/setting.py) 中的程式碼
修改成

``` python
ALLPAY_SANDBOX =  False
AIO_SERVICE_URL = 'https://payment.allpay.com.tw/Cashier/AioCheckOut'
AIO_SANDBOX_SERVICE_URL = 'http://payment-stage.allpay.com.tw/Cashier/AioCheckOut'
MERCHANT_ID = '您的商店 ID'
HASH_KEY = '歐付寶提供的 Hash Key'
HASH_IV = '歐付寶提供的 Hash IV'
RETURN_URL = 'Return URL' # 意義可能請您參考歐付寶的 Doc.
CLIENT_BACK_URL = 'Client Back URL' # 意義可能請您參考歐付寶的 Doc.
PAYMENT_INFO_URL = 'Payment Info URL' # 意義可能請您參考歐付寶的 Doc.
```

接著再請您參考 demo Django app 的範例
我的做法是透過 ajax 將使用者的 request 送給後端 Django view 做處理，然後再利用 Http Response 回傳 json (將 form_html 回傳至 ajax callback function) 至前端做轉址到歐付寶產生訂單。
另外，
`payment_info` dictionary 可以傳入的 attributes 請參考 
https://github.com/lockys/pyAllpay#how-to-specify-payment_info-dictionary

希望可以讓您成功使用! :smile: 
這個 repo 很 infancy，歡迎 PRs
